### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by artokun** [BlitzBanana/space-traders-2#1]
Is this project abandoned?

**Comment by BlitzBanana** [comment]
@artokun Not really, i don't have enough free time to work on it.
Have fun on your Spice Traders MMORPG :wink:

**Comment by artokun** [comment]
Bummer. Well if you ever want to revitalize it down the road feel free to use our spice-traders-js-sdk. We are building an event driven backend that you can use to interface with any client. You could just focus on the front end and let us handle the logic. It uses websockets to it's pretty fast! It won't be playable for a while but check back again in September.
